### PR TITLE
fix opening sheets in order

### LINKED ISSUE #489: Race Condition when hiding then immediately opening another sheet
Version: 10.1.1
React native: 0.81.4
Reanimated: 4.2.0

When running this snippet of code 
```
await SheetManager.hide("SublocationScanningCard")
await SheetManager.show("ScannedBarcode")
```

There is a race condition where the first sheet hides but the second one never shows. This isnt a problem when animation is turned off for the sheet itself but is still an issue if an override is passed when showing/hiding

https://github.com/user-attachments/assets/e72a482f-aba6-442f-a34a-28a8ff25e4bd

### PR DESCRIPTION
**Pull request by ammarahm-ed**
Closes https://github.com/ammarahm-ed/react-native-actions-sheet/issues/489

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -514,6 +517,13 @@ export default forwardRef<ActionSheetRef, ActionSheetProps>(
         }
         const onCompleteAnimation = () => {
           if (closable || isSheetManagerOrRef) {
+            const providerIndex = providerRegistryStack.indexOf(providerId.current);
+
+            console.log(providerRegistryStack);
```
Comment (fobos531) [inline src/index.tsx]: @ammarahm-ed should these logs be here?

Comment (ammarahm-ed) [reply src/index.tsx:522]: Fixed in 9242e327e214f525573f4c22688a1fedf94c55c0
